Traceback (most recent call last):
  File "C:/Users/tyarboro/Documents/scripts/atbswp/atbswp/ch10/errorExample2.py", line 5, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
